# Use postgres/example user/password credentials
version: '3.3'
services:
  spring:
    container_name: spring-server
    build:
      context: ./recipemanager-be
      dockerfile: Dockerfile_spring
    image: spring-server:latest
    ports:
      - "8081:8080"
  react:
    container_name: react
    build:
      context: ./recipemanager-fe
      dockerfile: Dockerfile.react
    volumes:
      - ./recipemanager-fe/src:/react/src
    ports:
      - "3000:80"
  db:
    container_name: primary-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
  db-mongo:
    container_name: secondary-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    ports:
      - "27017:27017"