# Use postgres/example user/password credentials
version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  db:
    image: mongo
    restart: always
    environment:
      POSTGRES_DB: recipemanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5